In [2]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
lst=list(range(1,25))
arr=np.array(lst)
print(type(lst))
print(type(arr))


<class 'list'>
<class 'numpy.ndarray'>


In [11]:
arr=np.array([1,2,3,4])

lst=list(range(5))
arr
# print(arr)
# print(lst)

array([1, 2, 3, 4])

In [10]:
arr = np.arange(1,25)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [14]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
arr=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[22,23,24,25]]])
arr
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [22 23 24 25]]]


In [22]:
arr=np.zeros((3,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
arr=np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# linspace() is used to create arrays with equal interval
arr=np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [28]:
arr=np.linspace(1,10,5).reshape(5,1)
arr

array([[ 1.  ],
       [ 3.25],
       [ 5.5 ],
       [ 7.75],
       [10.  ]])

In [33]:
arr = np.arange(0,30).reshape(5,6)
arr


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [34]:
#Reshaping 2D to 3D
arr = np.arange(0,30).reshape(5,6,1)
arr


array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14],
        [15],
        [16],
        [17]],

       [[18],
        [19],
        [20],
        [21],
        [22],
        [23]],

       [[24],
        [25],
        [26],
        [27],
        [28],
        [29]]])

In [36]:
#Reshaping 2D to 3D
arr = np.arange(0,30).reshape(3,5,2)
arr


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [45]:
arr=np.random.randint(1,5,9)
arr

array([2, 4, 4, 2, 1, 1, 4, 2, 1])

In [48]:
arr=np.random.randint(1,5,(3,3))
arr

array([[4, 2, 2],
       [2, 4, 4],
       [2, 4, 2]])

In [ ]:
arr=np.random.randint(1,5,(3,3,3))
arr

array([[[3, 2, 4],
        [2, 2, 2],
        [1, 4, 1]],

       [[4, 3, 4],
        [3, 2, 3],
        [1, 3, 2]],

       [[4, 1, 3],
        [3, 2, 3],
        [1, 3, 2]]])

In [51]:
arr=np.random.random(10)
arr

array([0.28536283, 0.62412547, 0.62998905, 0.90415887, 0.80399478,
       0.87233449, 0.83413855, 0.52470081, 0.13864321, 0.42663303])

In [62]:
arr=np.random.random((10,5))
arr
#arr.dtype
# arr.shape
# arr.ndim
#arr.size
arr.flatten()

array([0.85205039, 0.19721207, 0.79194734, 0.89872869, 0.5216486 ,
       0.34967682, 0.58667809, 0.68308773, 0.32320167, 0.42386157,
       0.76737293, 0.72756837, 0.33105645, 0.92430849, 0.86972352,
       0.25855924, 0.76713392, 0.1773916 , 0.64861685, 0.39154345,
       0.01345799, 0.30375989, 0.78324737, 0.13422768, 0.2666656 ,
       0.10800431, 0.4480508 , 0.06477258, 0.08437919, 0.74495504,
       0.66062308, 0.54525149, 0.00169194, 0.30389125, 0.54068323,
       0.98961077, 0.58314609, 0.09959062, 0.93945297, 0.42482838,
       0.40446791, 0.53916241, 0.43300316, 0.57617995, 0.04161039,
       0.32874383, 0.80280193, 0.76555485, 0.77058429, 0.11217015])

In [63]:
arr.ravel()

array([0.85205039, 0.19721207, 0.79194734, 0.89872869, 0.5216486 ,
       0.34967682, 0.58667809, 0.68308773, 0.32320167, 0.42386157,
       0.76737293, 0.72756837, 0.33105645, 0.92430849, 0.86972352,
       0.25855924, 0.76713392, 0.1773916 , 0.64861685, 0.39154345,
       0.01345799, 0.30375989, 0.78324737, 0.13422768, 0.2666656 ,
       0.10800431, 0.4480508 , 0.06477258, 0.08437919, 0.74495504,
       0.66062308, 0.54525149, 0.00169194, 0.30389125, 0.54068323,
       0.98961077, 0.58314609, 0.09959062, 0.93945297, 0.42482838,
       0.40446791, 0.53916241, 0.43300316, 0.57617995, 0.04161039,
       0.32874383, 0.80280193, 0.76555485, 0.77058429, 0.11217015])

In [67]:
lst=[1,2,3,4,5,6,7,8,9,10]
arr=np.array(lst)
arr.shape
arr.T.shape


(10,)

In [ ]:
lst=[[1,2,3],[4,5,6]]
arr=np.array(lst)
arr.shape
arr.T.shape

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]
