In [2]:
import numpy as np

In [3]:
a=[1,2,3,4,5,6,7,8,9,0]


In [5]:
np.array((1,2,3,4,5))


array([1, 2, 3, 4, 5])

In [7]:
arr=np.array(a)

In [8]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [9]:
type(arr)

numpy.ndarray

In [ ]:
lst=list(range(1,25))
arr=np.array(lst)
print(lst)
print(type(lst))
print(type(arr))



[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
<class 'list'>
<class 'numpy.ndarray'>


In [12]:
arr=np.arange(1,10)

In [13]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr=np.zeros((2,3))

In [15]:
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
arr=np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
arr=np.ones(10)

In [18]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
arr=np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [23]:
arr = np.arange(0,30).reshape(5,6)
arr


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [24]:
arr=np.random.randint(1,5,9)
arr

array([4, 2, 1, 3, 3, 3, 1, 3, 3])

In [27]:
arr=np.random.randint(1,5,(3,3))
arr

#(3,3) --->to convert in 2D

array([[4, 1, 2],
       [4, 1, 2],
       [4, 2, 4]])

In [28]:
np.random.random(10)

array([0.56630983, 0.77793646, 0.79899927, 0.40728972, 0.08436028,
       0.48045669, 0.05171306, 0.10451585, 0.85842622, 0.73030665])

In [29]:
np.random.random((3,3))

array([[0.04651492, 0.11729873, 0.91401116],
       [0.90254318, 0.40023355, 0.20482314],
       [0.77043002, 0.34284859, 0.38974114]])

In [30]:
arr.shape

(3, 3)

In [33]:
list_2d=[[1,2,3],[4,5,6]]

In [34]:
arr=np.array(list_2d)

In [35]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
arr.shape

(2, 3)

In [37]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [46]:
arr=np.random.randint(1,20,50)
arr

array([ 7, 12,  8, 15,  1, 17,  2, 18,  5, 10,  5, 12,  9,  5,  3,  5, 15,
        5, 18, 17, 15,  4, 10, 18,  5,  4,  7, 13,  7, 12, 13,  2,  9,  5,
       11, 11,  3, 18, 16,  6, 13, 17, 16, 13,  7, 19, 11,  5, 17,  1])

In [47]:
arr

array([ 7, 12,  8, 15,  1, 17,  2, 18,  5, 10,  5, 12,  9,  5,  3,  5, 15,
        5, 18, 17, 15,  4, 10, 18,  5,  4,  7, 13,  7, 12, 13,  2,  9,  5,
       11, 11,  3, 18, 16,  6, 13, 17, 16, 13,  7, 19, 11,  5, 17,  1])

In [48]:
arr[0:20:2]

array([ 7,  8,  1,  2,  5,  5,  9,  3, 15, 18])

In [49]:
arr=np.arange(60)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [51]:
arr.reshape(12,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [53]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [54]:
arr[-1]

59

In [57]:
arr=np.random.randint(1,60,(12,5))
arr

array([[38, 47, 22, 43, 15],
       [51, 19, 48,  1, 19],
       [10,  7, 49, 44, 59],
       [50, 24, 28, 18, 22],
       [ 2, 20,  2, 53, 52],
       [49, 59, 56, 53, 19],
       [25,  4, 16, 34, 51],
       [28, 40, 10, 27, 59],
       [18,  6, 41, 42, 12],
       [21, 41, 17, 20, 28],
       [39, 29, 28,  5, 34],
       [38, 33, 16, 18, 11]])

In [58]:
arr[11,4]

11

In [59]:
arr[-1][-1]

11

In [60]:
arr

array([[38, 47, 22, 43, 15],
       [51, 19, 48,  1, 19],
       [10,  7, 49, 44, 59],
       [50, 24, 28, 18, 22],
       [ 2, 20,  2, 53, 52],
       [49, 59, 56, 53, 19],
       [25,  4, 16, 34, 51],
       [28, 40, 10, 27, 59],
       [18,  6, 41, 42, 12],
       [21, 41, 17, 20, 28],
       [39, 29, 28,  5, 34],
       [38, 33, 16, 18, 11]])

In [61]:
arr[4,2]=200

In [62]:
arr

array([[ 38,  47,  22,  43,  15],
       [ 51,  19,  48,   1,  19],
       [ 10,   7,  49,  44,  59],
       [ 50,  24,  28,  18,  22],
       [  2,  20, 200,  53,  52],
       [ 49,  59,  56,  53,  19],
       [ 25,   4,  16,  34,  51],
       [ 28,  40,  10,  27,  59],
       [ 18,   6,  41,  42,  12],
       [ 21,  41,  17,  20,  28],
       [ 39,  29,  28,   5,  34],
       [ 38,  33,  16,  18,  11]])

In [67]:
arr=np.arange(0,225)

In [68]:
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [69]:
arr=arr.reshape(3,15,5)

In [70]:
arr

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124],
        [125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134],
        [135, 136, 137, 138, 139],
        [140, 141,

In [71]:
arr.shape

(3, 15, 5)

In [72]:
arr[0]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74]])

In [74]:
arr[0][2:7][0]


array([10, 11, 12, 13, 14])

In [75]:
arr[:,0:1,0:1]

array([[[  0]],

       [[ 75]],

       [[150]]])

In [79]:
lst1=list(range(1,25))
lst2=list(range(26,50))

In [80]:
lst1

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24]

In [81]:
lst2

[26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49]

In [83]:
z=lst1+lst2

In [84]:
z

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49]

In [91]:
z=lst1*lst2

TypeError: can't multiply sequence by non-int of type 'list'

In [85]:
x=np.array(lst1)

In [86]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [87]:
y=np.array(lst2)

In [88]:
y

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

In [89]:
z=x+y

In [90]:
z

array([27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59,
       61, 63, 65, 67, 69, 71, 73])

In [92]:
z=x*y

In [93]:
z

array([  26,   54,   84,  116,  150,  186,  224,  264,  306,  350,  396,
        444,  494,  546,  600,  656,  714,  774,  836,  900,  966, 1034,
       1104, 1176])